### PR TITLE
fix: argument in "vim.foo({bar})"

### LINKED ISSUE #102: Argument in some functions is not recognized if not preceded by whitespace
Consider
```help
vim.foo({bar})
```
Tree:
```lisp
(block) ; [1:1 - 2:0]
 (line) ; [1:1 - 2:0]
  (word) ; [1:1 - 14]
```

But
```help
vim.foo( {bar})
```
Tree:
```lisp
(block) ; [1:1 - 2:0]
 (line) ; [1:1 - 2:0]
  (word) ; [1:1 - 8]
  (argument) ; [1:10 - 14]
   text: (word) ; [1:11 - 13]
  (word) ; [1:15 - 15]
```

Needless to say, that affects much of our docs.

Works fine without the dot, though:
```help
nvim_foo({bar})
```
Tree:
```lisp
(block) ; [1:1 - 2:0]
 (line) ; [1:1 - 2:0]
  (word) ; [1:1 - 9]
  (argument) ; [1:10 - 14]
   text: (word) ; [1:11 - 13]
  (word) ; [1:15 - 15]
```

But only for the first argument; if there are more arguments and these are not preceded by whitespace (as is usual), these don't get caught:
```help
nvim_foo({bar},{baz})
```
Tree:
```lisp
(block) ; [1:1 - 2:0]
 (line) ; [1:1 - 2:0]
  (word) ; [1:1 - 9]
  (argument) ; [1:10 - 14]
   text: (word) ; [1:11 - 13]
  (word) ; [1:15 - 21]
```

### PR DESCRIPTION
**Pull request by justinmk**
(Continues https://github.com/neovim/tree-sitter-vimdoc/pull/103 )

Problem:
In "vim.foo({bar})", {bar} is not recognized as (argument).

Solution:
Add more special-cases for plain (word).

Closes #102

# Notes

- also improves this `(url)` case: https://github.com/neovim/tree-sitter-vimdoc/blob/755b8011907be9427f73e4f3989e9ece584f0aa8/corpus/url.txt#L42

### CODE REVIEW

**Comment by clason** [comment]
Now the first argument is no longer recognized...

**Comment by clason** [comment]
There's still a parse error (but not wrong highlighting) in
* `:h v_aB`

(but not in `map.txt` on `|,|` anymore 🎉 )

**Comment by justinmk** [comment]
> There's still a parse error in `:h v_aB`

Looks like the `{` in `"[count] [{"` is causing an error. Could be fixed by changing the `"` to backticks.

**Comment by clason** [comment]
Ah, I had assumed that the `ERROR` node would be rooted at the misparsed node, but you are right. This file (and map.txt) has a bunch of careless quotes that merit cleaning up. 

(I have hesitated to touch upstream docs so far, but if it's open season now...)

**Comment by justinmk** [comment]
This definitely improves things, but also causes a few errors. Will see if those can be avoided with some tweaks.

File: grammar.js [hunk 1]
```diff
@@ -80,10 +80,16 @@ module.exports = grammar({
       '{}',
       /\{\{+[0-9]*/,
       '(',
+      ')',
+      '[',
+      ']',
+      "['",
+      "']",
```
Comment (justinmk) [inline grammar.js:87]: Dropping `')'` and `']'` avoids 10 (out of ~30) new errors in a full `gen_help_html.validate()` run. And still passes the [new tests](https://github.com/neovim/tree-sitter-vimdoc/pull/103/files#diff-334e21593203e1c6431a705d373c69ad292ce95f8a3cc78fa032239819e01aec).

```suggestion
      '[',
      "['",
      "']",
```
